#----------------------------------------------------------------------
# This file was generated by /usr/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
index = []

ALIGN_BOTTOM = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAANUlE"
    "QVQokWP8//8/AymAiSTVoxoGjQYWCMXIyEhQKSRNMMKTRl1dHR7VTU1NUKNJTUuD0EkAqAkb"
    "EcYKpPgAAAAASUVORK5CYII=")
index.append('ALIGN_BOTTOM')
catalog['ALIGN_BOTTOM'] = ALIGN_BOTTOM
getALIGN_BOTTOMData = ALIGN_BOTTOM.GetData
getALIGN_BOTTOMImage = ALIGN_BOTTOM.GetImage
getALIGN_BOTTOMBitmap = ALIGN_BOTTOM.GetBitmap

#----------------------------------------------------------------------
ALIGN_MIDDLE = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAOElE"
    "QVQokWP8//8/AymAiSTVw0QDC4RiZGQkqBQSnozwYK2rq8OjuqmpCWo0qfEwCJ00CCOOZA0A"
    "/+cbEYsI0xAAAAAASUVORK5CYII=")
index.append('ALIGN_MIDDLE')
catalog['ALIGN_MIDDLE'] = ALIGN_MIDDLE
getALIGN_MIDDLEData = ALIGN_MIDDLE.GetData
getALIGN_MIDDLEImage = ALIGN_MIDDLE.GetImage
getALIGN_MIDDLEBitmap = ALIGN_MIDDLE.GetBitmap

#----------------------------------------------------------------------
ALIGN_TOP = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAMklE"
    "QVQokWP8//8/AymABUIxMjISVAoxmhFuQ11dHR7VTU1NUKOHgZOYSFI9qmHQaAAA7cQbEcOG"
    "FWwAAAAASUVORK5CYII=")
index.append('ALIGN_TOP')
catalog['ALIGN_TOP'] = ALIGN_TOP
getALIGN_TOPData = ALIGN_TOP.GetData
getALIGN_TOPImage = ALIGN_TOP.GetImage
getALIGN_TOPBitmap = ALIGN_TOP.GetBitmap

#----------------------------------------------------------------------
ALIGN_LEFT = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAWklE"
    "QVQokWP8//8/AymAiSTV5GhggVCMjIwElUIczwj3Q11dHR7VTU1NUKNJ9TQWJ+E3ggmuqLa2"
    "tra2lqCF1HASJkA2lHAowcOH2k7CZRB2J6E5gyInkZz4AEywNfHRM0phAAAAAElFTkSuQmCC")
index.append('ALIGN_LEFT')
catalog['ALIGN_LEFT'] = ALIGN_LEFT
getALIGN_LEFTData = ALIGN_LEFT.GetData
getALIGN_LEFTImage = ALIGN_LEFT.GetImage
getALIGN_LEFTBitmap = ALIGN_LEFT.GetBitmap

#----------------------------------------------------------------------
ALIGN_CENTER = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAZElE"
    "QVQokaWSwQrAIAxD1+Fvpwd/PB4cpZvVUfUiSJq8BoXklTl3Sr0zUPolIr/SDi+2g6ou1LXW"
    "xzq7dBmfPN5oFyxNEgCAMPwAaV2U+b4SZkVZRWdIM7CPY5DgwTzMJlL68zV1wTXxa/Vd6wAA"
    "AABJRU5ErkJggg==")
index.append('ALIGN_CENTER')
catalog['ALIGN_CENTER'] = ALIGN_CENTER
getALIGN_CENTERData = ALIGN_CENTER.GetData
getALIGN_CENTERImage = ALIGN_CENTER.GetImage
getALIGN_CENTERBitmap = ALIGN_CENTER.GetBitmap

#----------------------------------------------------------------------
ALIGN_RIGHT = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAXklE"
    "QVQokbWSwQ6AMAhDrdlvlwM/Xg+YxahjYUYuHCjktQGStkrtJfXKQosGYCoNeHQPZpao3f08"
    "XTXd8vEVNU5PTEsiSbKDfEPKs7qnFDXK6oeUnnjvSCO8daTy8x2e0jXxTrfbVQAAAABJRU5E"
    "rkJggg==")
index.append('ALIGN_RIGHT')
catalog['ALIGN_RIGHT'] = ALIGN_RIGHT
getALIGN_RIGHTData = ALIGN_RIGHT.GetData
getALIGN_RIGHTImage = ALIGN_RIGHT.GetImage
getALIGN_RIGHTBitmap = ALIGN_RIGHT.GetBitmap

#----------------------------------------------------------------------
ICON_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAA3NCSVQICAjb4U/gAAAGUklE"
    "QVRIidWWS49bSRXHz6Oq7su+dj/c7W53ujsZAklmQjQgDQIkhmyQWLDgO/ABWPJl+A4sEGKD"
    "EBJCQqNRJhpGIlHeJJlut9tt+9q+99brsLBmWCIWGYnfps6iqs7Rv/51dADeMQgAIoL4PwTT"
    "3+Lm8M6v4L9uhv8s7zL4fwazLBsMhoQ4uRzneaEUEzEziUDTtEWRW2uZUatke3u7ruvZ1azo"
    "dFarqlpWzOycU0oZYxKtAVET9fo7k8lZFCDmZl1zWZbr1Wpnd897ByDBewBgJudcCN57T4gh"
    "Ruud0YYI67Z2zoYY6roWESJyzhVFUWQpRNgfjpr1XKKwNmmSAAH1etv9fn+1Wh6NTtMkJeYQ"
    "grXOOee9b9sGCb33wbl1XWdpZpQmxK99AgCIQMQA0u/1FCORCojB+7puTJJQ8KHb61vbVMvF"
    "/nAUY2TmEAIze+9jjN77PM9FYgwhRkQiJh1jjDECgIiIACE2jc2K7nh81rY2NYnSWpkEgVkb"
    "5Z27dnR9tZx5H7b625PJOISglNrckmVZlnYQoW3bTtGNElnxarVyzhKRxAiAWZbnne66mrfW"
    "ClKS5svVcqM597e2CHGxmI9Gx+tVZdKsrmtr2xCCiHjvRaTsdDt5N0mTk+MbALBaL5fLRQgB"
    "EUSEmAGEFS9Xq263ByDzat60DRIQK8rSVGudp+nl5Hx/OJrPpqPRiQiEEAAEAJxzPoRe2Tcm"
    "2z84ONgfJSZlVrJRB0Qg1vV6Nr1K0myxmFeLubctI0gUECClDCEBSmubp08f9bd23r551e12"
    "N/ogolKqadrR0YkIMHEEPByOCJGIEBEBCQkRkyxZr5YhRtZGGZNmRa/s7e7uKq1MYhKlFABc"
    "Xl68ePGk0+lWiwUAgAACeB+adj2bz3d3h8ODg2VVI4IxifO+bVutdQwREJq6YWbxIUszgAhI"
    "RNjJiMuyXNcrb62zjdFGabOYz5DIWosIAhhj2Hip1+vffv9WmmYXF2fT6YW11nsPACEGZtZa"
    "Bx/yPM/SfH84Yg0H+8nHP75DrHQI0flQrVbT2WRZzUWkbVsACFFERGvtvZ9Ox1leTKfzvMiO"
    "j0+UMgCwSSwiIQQAYMVFp7t3cDieToqST68f3vr2de6VJRGKCAgwK1YcQtxY6GsAIM1yrcze"
    "YG84PESJ0+llVVXr9Wrz40ySaKV6ZXn//t179wbjy/Xd2wc33zu9eXKojDFEHKJfLSvvvQjg"
    "5vG+IsaISEopZrTWDQ8G52dvRofXJpOLyeUYAIgw+tDbyX/z61/uH+0+efavX/zsg7JIvnVy"
    "7a9/fqCIOdWGdL6zM1jMp8tq6byNwcevQEQAIWQRbJoaifM8H4/Pq+ViUwchJsb84KMfGqw7"
    "Gr5/94bzztbxwSdf/O5PD1Xb1GXHvHe6/fj5JAqkRQfqOhUgtm3beu837aAoOsF7rfV8dlWW"
    "JSKWZX9Rzdu2YaKs6Hzvo49fTGdfPHk03FURwiefPnvw+evaOlX2ev1y50cfHh0f77x8O375"
    "eprnO4Pd4vE/37x69eVquQKAEKMPbjw5r9v24Wf/uHHjRlZkgLBpvUjEjH/8w+/Lcmt8fnY1"
    "PXOu9iG01jnveW+wl3dKivH+T+/2+9393ez2d4b3Pjj9+U/ubBXq7SWs1xUINm2tlUbAarHw"
    "3oUQXjx7QkS2bYhQsWII08vzdb0QiNZ6AXTOJ0nG+8MhCCxqfP3yzYe3jo4Od48PtjPiydnV"
    "w6dy/eb7T588CsEDYtPUPngEsm07vbw8H7+tllWUSESJScpOF5UKMbStjTEgqyzLe+UWDwZD"
    "xUyM86X/y98eoz59/eX608+e//3zq2fPXj5/+rhp1tY5772AeO+JaF2vifHi4kxrHWNQSmVZ"
    "6kW00i6Euq6JVZ510jQzOsE7t7+LBIpVr18qxdWiCt5HiUprRJQQ54vZ5HLSNC0AMLNS+mB4"
    "VC0X3rcbFzBzp9NRSg8GAwRorUXgTrcs8mI2u1ICQkjO+dnVPE1TIErSRJvEO+u8B0JEMibZ"
    "JAAAkRiiFwkbYoxEFGM0xoigMUmS5giolPLeJibhosjatiUmpVQUkCiAZG3LrGxrCalpW++9"
    "tVZEmFlEvHdl2Wuamog2/RwAiqKjlEZCrY1EqesVs2qa9bueWr4Z3unoSO+u7m+IfwO3YTXr"
    "4uYBSgAAAABJRU5ErkJggg==")
index.append('ICON_32')
catalog['ICON_32'] = ICON_32
getICON_32Data = ICON_32.GetData
getICON_32Image = ICON_32.GetImage
getICON_32Bitmap = ICON_32.GetBitmap

#----------------------------------------------------------------------
ICON_48 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAIAAADYYG7QAAAAA3NCSVQICAjb4U/gAAAMTUlE"
    "QVRYhe1YSY8k13GOiPfy5V5LV3X1OtPTo+FoKFGUKAmEAEuAYcM3++Kjr5Z/lAH/ABnwzRAk"
    "H2QDJk1bgEVB9HBIict0D6fX6rWycnlr+JClNuCDCMg6+DDfoVCvKuvVl/G++CIiAV7hdwMB"
    "gJkBABH7j37v5eXfrTad/BB+/63+gIT+IEv68iC+wiv8TiAApGlalsOdnfsvjw66tlUqHg2H"
    "dVMTCURghihSdb1ExDRNALDr2iiKrLXr0/UiLwDx4OC5ilQcx1p31rvlcimlDCH0OpVSDodD"
    "DEHrLsvLRKnhcO387Kg1hpAYIUvTarFwIZzP5wIAhsNh13XWuu3tnbatrXVE1HUdIqRpwszO"
    "WeYQQkBE77yQsl8CUpqm1tnlslJx3OnOBx8Ca60BgIgAIIQAAKPRSEUSmBFwe/tetbhk75AQ"
    "pRyUpdHGcSiL8urqigAgTbPJZKJ1a41fX98elIV1Nooi733TtM45Y4z3LoTQ1HUUCe+d1loQ"
    "te3SOBdFUZFlhJCmKRHh/zoCxBBYCOG9z9NsfToDDEAYkBhl8KGqKuvdYDCwzkGf9lmWG2PW"
    "1iZ1W6VJXhbjfussy733Ukoi8j445xjAMwui/sicddbYLMkCYwjBaA0A2mgACMyI2HuMlJJ9"
    "cM4GgKwsry4vMIBnRGQpScUxM9R1E0XRipC1fmfnnjGdd+bq+mJ9tsGM1tqua4nIGCOE6IMf"
    "QtBdB4hlORBSBA6E5BxrY8piKIQKIQADMwMzIgbve40u66WzYbqxdfryZdvUbddGkUyiGFH4"
    "AEKqQTGUQgJA/0/OGLv/4FHXdsxuPp9/663vnhwdOWu01kQkhEBE55wQIoqiWMVJkofgrXXA"
    "GEdKCtJGy0i1beu8c84hoiDhgweA0XhSLW7zYpAlycXlGQMG4ChKRRS1bWu0Zg7adMzh+uaG"
    "AGBtbcLsXx69mM02i7xkbz/79JPHj1/vw661ds712rTWOudICIFCyUSSGAzKjc1NFWeCFBHe"
    "ZRYicPC8WqLzYbw2eXH0BSC6EIpyzBxubq67rnXeEWEcJ4FhFaGiKEII3rvq9ma2vjWdTi8v"
    "TlBIpdLlcoGI3vu+1PSnhkhxEk8ns6pePnny+iAfrk835lcXTVN1Xeu98z4gkiAMgZHIW6ti"
    "tVjcOGuzvBiOxovbm65ddtr44L33ROS9j+Pk6uqSAKAoBmmaZWlWlMX19YVnWF/fvro6m802"
    "sqzoY9Pfd//GGB1JRYBpnCBKknI2m25v7gJTHMeIdHc9AxNRp7u2abTWKk6EjI6PvujaOjAD"
    "+0iQIEIAQYJ9WIn65ubKOW2NtkZX9e3Ry0NAHI9mv/742Wxjkxm89xwCAiCilNJay4Db2/eH"
    "g2HbdlKos/l8Y302KAaxiololV4IBEhIIQQp5XA4cNbe3l6RQEYERCRiAEFCClkWRZYXK0I7"
    "O/dHw+n6+qZSiSShTfP8+Scu2CRRZyfHSZIwQ+DAzD2nOE7Oz88CQ5oNAMRrT75irD0/u3jt"
    "8RMZSSKBiMzAQCRkr24GXiwqYwwCIYhIKiKZJGlZDmcbG6PxuBwMlIQVobZtrTVt12Z5ubm1"
    "OxiMQwgnxy+RkAQZowE4BCAiItS6X9rLq0tt9b37D4SI4jjd3N7J84JQxLESQjCztTZSkXU2"
    "cAg+ICIJ6nTnvI/jOM9SJUUIvq6X3pk44q8/XluJejAYdro1uvPOVDe3KlLD8ZgQb2+vozh2"
    "1nrnhcBeqgBgjBWC2rYdjyZpmuzt3/OO7t3fevpfHzTN0jlrrb1z6t4CpJS9WRNRmiZRpAij"
    "4XgyHA2Bu62t7I2v3fvm4/s//tkvqHd3BojjNAQWES2X1/Ozk7ZrkWhZVc45QPCOETGEIIQA"
    "YK31orr2XnfaSpVY097f293e3gGApm37fGRmrTUz90lERMCslBIk4zh7481vMvujo8OHjybb"
    "2xtPHj3Y/8oOAEgA8D4EH9quDc6GwN5bAAzWcgBEvMuXPt2iKHLOMTMiHL548cab352fnXXa"
    "JvkgjpPxaFJV1TJUxvBdkKy1cRwzMwMQivFkOhwNfvX0qQe/u7+7u7M+LMvp5tQZXhEiBCIK"
    "IYhICeaYYmZg4KZpgg13+/bMjDHMjEhKJVLg888+I+C9/X32viyK8Xhyu7ixzrZtc+cUURRF"
    "UdQLazodf+/tvSevr3/w4eidf//08aP16WC0trG1vT7+yT++uyIkI5mmqQ++WiyM0RzYe4+E"
    "iCSl9N7f+S8z95pAxFgldV2VZQaAW5szIljWzf6Dfe9M17S3N1dIxMx9ffXeE9KbX3v8w7/+"
    "M+vM5cXF3u5w9y+/IYDKQfnkwVZ9cfkv7z5bEYpkJEgIIQeDgbXGOgsM1rm2bZ2z3nv4LRv4"
    "n1GBnTdFMWja+uzszDg7Ho+UUiH4arkkIZGoP2JC4BCAeW9342/+6jv3tkcuyCRW19eLJEvW"
    "iqQsEuX13/79v3VMK0LOuSxPWGCaZXEcX13OrdYhcFnmbd0gkrW2L653d8zMwfNgPPYWWt8i"
    "cpxkSsmDw+OT05dCyv4yIkIEQirL0Vvf+cHnhzdlfjyYTPe2xrsbpQ+8uNXVdfWjH73z4cEV"
    "IKwIGau1kTvb4+tFV1WGhFBpprKsXlaAXRLHQkjn7G8LGXDfYCBtbm0sbpv9hw+95+vrq+ls"
    "Oj8/A6bxaHJzc71cVr06SYjhaPr2975/fnb603d++dX7Fztb4yjPmO1HH538+Ce/Or1ceuBV"
    "vwsA0+l6mco//aP9z4+Xz35zXFW60/r8vCkHg/F60tY16i4Ej4iCiFe/xCROLi7nzOJ2sTg/"
    "Pa2rerI2U9Fng3J4MZ8LEgAASIQkpUQIH3/06/2Heyr+439+772m+cg1l9WiWTSND2i908b0"
    "RywAYG/voRDp1gjffOPh3oPpeC2frCVJFm9uDP7iz7+xe2+WxsraYIxdGS4RM6tIad1FSu3s"
    "3OuaJiAY7cph+sv335+srx2fHDEzIRIhCVkU2enxy2cfPn3/Fz+fnz2vbq6rum2MsTZY573z"
    "DIxIy2UlAGC2PptMpoeH13/yg/1itJZnMTJvb+b7DyZ5Xj55NPv+t1/71len88umtVHXNYKI"
    "GdquFUIQiSRJDg6eCxJ5nl5dXZ6fnVbVIsvzqrpFBCQUJCIhBCF7a50WUpIgba2zIVKRs9Zz"
    "UCoeDEbz+bkAgI2NTQAerK29+96zrz8YzaZro8lwOs73760P8ziPc/Lu5Iv5Wbf98OGjF4fP"
    "ObgQQuBAhEabJFZNUyOKPE+ff34QSXFw+GnTNgCrRhaRYqXWBkMS0jM756y1EHxvB4wYx3Ga"
    "5EmanJwc9xHaAGAOQaj8P/7zM9vUu7NpGudSyjQWN+fXv/nk4l8/6AbDibX65dGhcyaEwABC"
    "CG3aRVXledl2rdGmbqqT0+O2XVpn+2sIRaxUJKVSsQcgIVzw1lnnvQuBSI3HQ6Wy0XgSgj8+"
    "fikBIFIJADZdlyNRFP/s5wdPn/Nb335bd3Ng//HHT5mGX7w4cB9/YKxBDs733Sb0Hbe1Zlkv"
    "ppONwy8ONzY2SGBgVioGYGMMCSIikvKmXhZ5IYUMPhitESlJ0jQpvA9SoNGtd36VZU1dk0Ap"
    "ImvMaDQarY2a7uKn//QPzN45DxBkdCkVlOWwbVvEsmlr7ifFEBARINzeXnHgyWRaVYvr64s8"
    "z9u2lVIyMzN7Ds478AgIQlKk5DAaeR+YEQkm42ms1MV8nuf5ilCcKGuMDw6cWFR1UeRNqxm8"
    "FCSI8ryw1izrGlMhpFxWVZblXdd573v361/brvZ+rW3rvt6FELqu642UiAQJJLLGpWlWlkOt"
    "NQAWRaFUjEhd2xIKKcWKUNd1QghCqU3HzByYBMZJKhCZmYRgy0IKZmZAGUVSRiE0vV/36Kc2"
    "bVrnTD8z9dOcc84733VdkiSxVCSElDJ4SNM8BLbGOeulkERYFEWcqJUPjUbDetlIKUIISEQk"
    "ggfvrPPMwNWyiiIlBHVNK6PIGGOMZua+6FLfRyIyB2v12tqUSGjdCSFWzwKC74txnueEhIRE"
    "FDznRe6sc85oo1WcVIvb28XN6dmpAACl4iiSXdeqWFlrO90SgZQSCZ0LsYqzPK+XdWDup3Rr"
    "rTH6rvnqtdIz07rrusZ7fzfYW2v7b7MslVGEiNaacjCoFgvrrDaGiIxu26411lxcXMArvML/"
    "Ea+eU38Z/t8ReoUvw38DwoQ90Ega5wIAAAAASUVORK5CYII=")
index.append('ICON_48')
catalog['ICON_48'] = ICON_48
getICON_48Data = ICON_48.GetData
getICON_48Image = ICON_48.GetImage
getICON_48Bitmap = ICON_48.GetBitmap

