#
# Makefile-Rules for PhotoFilmStrip
#

appname = photofilmstrip
displayname = PhotoFilmStrip
srcdir = .

prefix = /usr
datarootdir = $(prefix)/share
pixmapdir = $(datarootdir)/pixmaps
appdir = $(datarootdir)/$(appname)
bindir = $(prefix)/bin
desktopdir = $(datarootdir)/applications
localedir = $(datarootdir)/locale
docdir = $(datarootdir)/doc/$(appname)

mkdir = mkdir -p --

