.TH USAGE: "1" "November 2010" "Usage: photofilmstrip [options]" "User Commands"
.SH NAME
photofilmstrip \- Slideshow creator with Ken Burns effect
.SH SYNOPSIS
.B photofilmstrip
.SH "SEE ALSO"
.BR mencoder (1),
.BR photofilmstrip-cli (1).
.SH AUTHOR
photofilmstrip was written by Jens G\[:o]pfert.
.PP
This manual page was written by G\[:u]rkan Seng\[:u]n <gurkan@phys.ethz.ch>,
for the Debian project (but may be used by others).
