#!/usr/bin/python
# -*- coding: utf-8
"""
    Contributed by Yoandy S <yoandy.shyno@gmail.com>
"""
import sys
import os
import time
import glob
import subprocess
from photofilmstrip.CLI import main as photofilmstrip_cli
from photofilmstrip.core.Project import Project
from photofilmstrip.core.ProjectFile import ProjectFile
from photofilmstrip.core.Picture import Picture


_duration = 0
_secsperimg = 10
_aspect = (16, 9)


def make_project(path, project_name):
    project = Project()
    images = [Picture(picpath) for picpath in glob.glob(path + '*.jpg') +
              glob.glob(path + '*.JPG')]
    global _duration
    global _secsperimg
    _duration = len(images) * _secsperimg
    project.SetDuration(_duration)
    project.SetPictures(images)
    project_file = ProjectFile(project, os.path.join(path, project_path))
    print(os.path.join(path, project_path))
    project_file.Save()


def get_images(path, WD):
    images = glob.glob(path + '*.jpg') + glob.glob(path + '*.JPG')
    for p in images:
        subprocess.call(["convert", p, "-resize", "x1440",
                         os.path.join(WD, os.path.basename(p))])


if __name__ == '__main__':
    WD = '/tmp/'
    WD += str(int(time.time())) + '/'
    os.mkdir(WD)
    # Collect data
    if len(sys.argv) < 2:
        print ("USAGE: %s <directory>" % (sys.argv[0]))
        exit()
    else:
        path = os.path.normpath(sys.argv[1]) + '/'
    project_name = 'photofilmstrip-prj-' + str(os.stat(path).st_ino) + '.pfs'
    project_path = WD + project_name
    if os.path.exists(project_path):
        print ("WARNING: Project file already exist, will be overwritten")
    get_images(path, WD)

    make_project(WD, project_name)
    sys.argv = [sys.argv[0]] +\
        '-p {}  -o {} -t 2 -f 5'.format(project_path, WD).split()
    photofilmstrip_cli()
