#!/usr/bin/python
# -*- coding: utf-8
"""
    Contributed by Yoandy S <yoandy.shyno@gmail.com>
"""
import argparse
import sys
import os
import glob
from photofilmstrip.CLI import main as photofilmstrip_cli
from photofilmstrip.core.Project import Project
from photofilmstrip.core.ProjectFile import ProjectFile
from photofilmstrip.core.Picture import Picture


_duration = 0
_secsperimg = 10
_aspect = (16, 9)


def make_project(path, project_path):
    project = Project()
    images = [Picture(picpath) for picpath in glob.glob(path + '*.jpg') +
              glob.glob(path + '*.JPG')]
    global _duration
    global _secsperimg
    _duration = len(images) * _secsperimg
    project.SetDuration(_duration)
    project.SetPictures(images)
    project_file = ProjectFile(project, project_path)
    project_file.Save()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate video from images in\
                                     a directory.')
    parser.add_argument("directory_path", help="Path of directory with source\
                        images.")
    parser.add_argument("-d", "--destination_path",
                        help="Path where output files will be created.")
    args = parser.parse_args()
    if not args.destination_path:
        WD = os.path.join(args.directory_path, "output")
    try:
        if not os.path.exists(WD):
            os.mkdir(WD)
    except PermissionError:
            print("Permission denied: error creating directory.")
    path = os.path.normpath(args.directory_path) + '/'
    project_name = 'photofilmstrip-prj-' + str(os.stat(path).st_ino) + '.pfs'
    project_path = os.path.join(WD, project_name)
    if os.path.exists(project_path):
        print ("WARNING: Project file already exist, will be overwritten")

    make_project(path, project_path)
    sys.argv = [sys.argv[0]] +\
        '-p {}  -o {} -t 2 -f 5'.format(project_path, WD).split()
    photofilmstrip_cli()
